/**
 * Manifest schema for extracted components.
 * Each extracted component has a sidecar `extracted-{slug}.json` next to its
 * .tsx / .html / .css / .png files. This is the source of truth for metadata.
 *
 * The manifest is:
 * - Written by extract-tool/server.js after codegen
 * - Read by src/features/builder-registry/blocks.ts via import.meta.glob
 * - Committed to git → synced across machines
 */

export type ExtractedCategory =
  | "hero"
  | "nav"
  | "footer"
  | "pricing"
  | "cta"
  | "faq"
  | "feature"
  | "testimonials"
  | "content"
  | "other";

export interface ExtractedPropSchema {
  /** Prop key in the component (e.g. "headline") */
  name: string;
  /** Display label in the Builder properties panel */
  label: string;
  /** Builder editor type */
  type: "text" | "textarea" | "image" | "boolean" | "select";
  /** Default value */
  defaultValue?: string | boolean | number;
  /** TypeScript type as a string (e.g. "string", "boolean") */
  tsType?: string;
}

export interface ExtractedManifest {
  /** Schema version — bump on breaking changes */
  schemaVersion: 1;

  /** URL-safe slug (e.g. "stripe-pricing-toggle") */
  slug: string;

  /** Display name (e.g. "Stripe Pricing Toggle") */
  name: string;

  /** Component version — bump on re-extraction */
  version: number;

  /** Short description, ideally generated by LLM */
  description?: string;

  /** Category for filtering in the Builder/Library */
  category: ExtractedCategory;

  /** Free-form tags (e.g. ["dark", "gradient", "centered"]) */
  tags: string[];

  /** Source URL the component was extracted from */
  sourceUrl?: string;

  /** ISO8601 timestamp of extraction */
  capturedAt: string;

  /** Viewport size at capture (e.g. "1440x900") */
  viewport?: string;

  /** Editable props detected during codegen */
  propSchema: ExtractedPropSchema[];

  /** Default values keyed by prop name */
  defaultProps: Record<string, unknown>;

  /** Health flag — set by smoke-render check */
  health?: "ok" | "warning" | "broken";

  /** Optional fields populated lazily */
  embedding?: number[]; // semantic search vector
  visualHash?: string; // perceptual hash for visual similarity
  lastUsedAt?: string; // last time used in Builder

  /** Files associated with this component (relative to manifest dir) */
  files: {
    component: string; // e.g. "extracted-{slug}.tsx"
    html?: string;
    css?: string;
    thumbnail?: string;
  };
}

/* ─── Runtime validation (lightweight) ──────────────────────────────── */

export function isValidManifest(m: unknown): m is ExtractedManifest {
  if (!m || typeof m !== "object") return false;
  const obj = m as Record<string, unknown>;
  return (
    typeof obj.slug === "string" &&
    typeof obj.name === "string" &&
    typeof obj.version === "number" &&
    typeof obj.category === "string" &&
    Array.isArray(obj.tags) &&
    Array.isArray(obj.propSchema) &&
    typeof obj.files === "object" &&
    obj.files !== null
  );
}
