/**
 * 🔄 RESUME from Stage 4 — uses saved master prompt v2 from previous run
 *
 * Reads: runs/2026-04-06T22-11-48-272Z/stage-4.json
 * Runs:  Stage 5 (Opus generator) → Stage 6 (Sonnet reviewer)
 * Saves: result.html
 */

import { claudeCode } from 'ai-sdk-provider-claude-code';
import { generateText } from 'ai';
import dotenv from 'dotenv';
import { readFileSync, writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
dotenv.config({ path: join(__dirname, '../../.env') });

const PREVIOUS_RUN = '2026-04-06T22-11-48-272Z';
const runDir = join(__dirname, 'runs', PREVIOUS_RUN);

console.log('📂 Loading saved state from:', runDir);
const stage4 = JSON.parse(readFileSync(join(runDir, 'stage-4.json'), 'utf8'));
const brief = readFileSync(join(runDir, 'brief.txt'), 'utf8');
const masterPromptV2 = stage4.output;

console.log('📝 Original brief:', brief);
console.log('📏 Master prompt v2 size:', masterPromptV2.length, 'chars\n');

function cleanCode(text) {
  return text
    .replace(/^```html\s*/i, '')
    .replace(/^```jsx?\s*/i, '')
    .replace(/^```\s*/i, '')
    .replace(/```\s*$/i, '')
    .trim();
}

function extractJSON(text) {
  const jsonMatch = text.match(/```json\s*([\s\S]*?)```/i) || text.match(/```\s*([\s\S]*?)```/);
  const jsonStr = jsonMatch ? jsonMatch[1] : text;
  try { return JSON.parse(jsonStr.trim()); } catch {
    const objMatch = text.match(/\{[\s\S]*\}/);
    if (objMatch) { try { return JSON.parse(objMatch[0]); } catch {} }
    return { raw: text };
  }
}

async function callClaude(model, system, prompt) {
  const result = await generateText({
    model: claudeCode(model),
    system,
    prompt,
  });
  return {
    text: result.text,
    tokens: (result.usage?.inputTokens || 0) + (result.usage?.outputTokens || 0),
  };
}

const STAGE_5_SYSTEM = `You are an expert HTML/CSS/JS developer who creates premium UI components.

Output:
- Pure HTML with Tailwind CSS classes (use class= not className=)
- Inline <style> tags for custom animations/keyframes
- Inline <script> tags for interactivity (vanilla JS, three.js if needed via CDN)
- Just the markup, no <html>/<body> wrappers
- No markdown fences, no explanations, no "Here's the component:"
- Start directly with HTML
- Assume Tailwind CDN and these fonts loaded: Fraunces (serif), Inter (sans)
- For three.js: load from https://cdn.jsdelivr.net/npm/three@0.160.0/build/three.min.js`;

const STAGE_6_SYSTEM = `You are a senior code reviewer specializing in premium UI components.

You review code generated by another AI model and:
1. Check if it actually works (syntax, no broken imports, valid three.js calls)
2. Check for AI slop (generic copy, predictable layouts, missing micro-details)
3. Check accessibility (ARIA, semantic HTML, keyboard nav)
4. Check responsiveness
5. Check if hover/focus states are present
6. Check if the original brief is respected

Then you classify severity:
- "high": broken code, missing core feature, brief not respected → needs regeneration
- "medium": works but has slop or quality issues → fix in place
- "low": minor polish needed → fix in place
- "none": already good → return as-is

Output ONLY this JSON format (no markdown fences):
{
  "severity": "low|medium|high|none",
  "issues": [
    { "type": "slop|bug|a11y|responsive|brief", "description": "...", "severity": "high|medium|low" }
  ],
  "summary": "one-line summary",
  "fixedCode": "the full corrected HTML code (only if severity is medium/low/none, otherwise empty string)"
}

For "fixedCode": output the COMPLETE corrected HTML with all fixes applied. Same format as input (no markdown fences).
If severity is "high", set fixedCode to empty string.`;

// ─── STAGE 5 ───────────────────────────────────────
console.log('🚀 Stage 5: Generator (Claude Opus 4.6)...');
const t5 = Date.now();
const r5 = await callClaude('opus', STAGE_5_SYSTEM, masterPromptV2);
const code = cleanCode(r5.text);
const t5dur = ((Date.now() - t5) / 1000).toFixed(1);
console.log(`✅ Stage 5 done: ${t5dur}s · ${r5.tokens} tokens · ${code.length} chars\n`);

writeFileSync(join(runDir, 'stage-5.json'), JSON.stringify({
  status: 'done',
  duration: t5dur,
  tokens: r5.tokens,
  model: 'Claude Opus 4.6',
  label: 'Generator',
  output: code,
}, null, 2));

// ─── STAGE 6 ───────────────────────────────────────
console.log('🛡️  Stage 6: Code Reviewer (Claude Sonnet 4.6)...');
const t6 = Date.now();
const reviewPrompt = `Original user brief: "${brief}"

Generated code to review:

═══ CODE START ═══
${code}
═══ CODE END ═══

Review this code thoroughly. Output JSON with severity, issues, summary, and fixedCode.`;

const r6 = await callClaude('sonnet', STAGE_6_SYSTEM, reviewPrompt);
const review = extractJSON(r6.text);
const t6dur = ((Date.now() - t6) / 1000).toFixed(1);
console.log(`✅ Stage 6 done: ${t6dur}s · ${r6.tokens} tokens`);
console.log(`   Severity: ${review.severity}`);
console.log(`   Issues: ${review.issues?.length || 0}`);
console.log(`   Summary: ${review.summary}\n`);

const finalCode = review.fixedCode && review.severity !== 'high' ? review.fixedCode : code;

writeFileSync(join(runDir, 'stage-6.json'), JSON.stringify({
  status: 'done',
  duration: t6dur,
  tokens: r6.tokens,
  model: 'Claude Sonnet 4.6',
  label: 'Code Reviewer',
  output: review,
  finalCode,
}, null, 2));

// ─── BUILD PREVIEW HTML ───────────────────────────
const fullHTML = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Resumed Pipeline Result</title>
  <script src="https://cdn.tailwindcss.com"></script>
  <link href="https://fonts.googleapis.com/css2?family=Fraunces:wght@300;400;700;900&family=Inter:wght@300;400;500;600;700;800&display=swap" rel="stylesheet">
  <style>
    body { font-family: 'Inter', system-ui, sans-serif; margin: 0; }
    .font-serif { font-family: 'Fraunces', Georgia, serif; }
  </style>
</head>
<body>
${finalCode}

<div style="position:fixed;bottom:16px;right:16px;background:rgba(0,0,0,0.85);color:white;padding:10px 14px;border-radius:8px;font-size:11px;font-family:monospace;backdrop-filter:blur(8px);z-index:9999">
  ✅ Resumed from Stage 4 · Stages 5+6 done · Severity: ${review.severity || 'unknown'}
</div>
</body>
</html>`;

const previewPath = join(runDir, 'preview.html');
writeFileSync(previewPath, fullHTML);

console.log('━'.repeat(60));
console.log('🎨 PREVIEW READY!');
console.log('━'.repeat(60));
console.log('📂', previewPath);
console.log('');
console.log('Review summary:', review.summary || 'N/A');
console.log('Issues found:', review.issues?.length || 0);
if (review.issues?.length) {
  review.issues.forEach((issue, i) => {
    console.log(`  ${i+1}. [${issue.severity || '?'}] ${issue.type}: ${issue.description}`);
  });
}
console.log('━'.repeat(60));
