/**
 * 🧪 TEST GEMINI - Génération + Preview HTML
 *
 * Run: node src/ai/test-gemini.mjs
 *
 * Génère un composant et crée un fichier HTML preview
 * que tu peux ouvrir dans ton navigateur.
 */

import { GoogleGenerativeAI } from '@google/generative-ai';
import dotenv from 'dotenv';
import { writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
dotenv.config({ path: join(__dirname, '../../.env') });

const apiKey = process.env.GEMINI_API_KEY;
if (!apiKey) {
  console.error('❌ GEMINI_API_KEY manquante');
  process.exit(1);
}

const genAI = new GoogleGenerativeAI(apiKey);

const model = genAI.getGenerativeModel({
  model: 'gemini-2.5-flash',
  generationConfig: {
    temperature: 0.7,
    maxOutputTokens: 8192,
  },
});

// 🎨 ANTI-SLOP SYSTEM PROMPT
const SYSTEM = `You are an expert HTML + Tailwind CSS component generator.

ANTI-SLOP RULES:
- Asymmetric layouts, NEVER centered hero
- Editorial typography: large display, tight tracking, weight contrast
- Maximum 2 colors + 1 accent
- NO generic copy ("Get Started", "Build Better", "Learn More")
- NO emoji, NO Lucide rocket/sparkle icons
- Custom easing: cubic-bezier(0.32, 0.72, 0, 1)
- Real specific copy
- Strong visual hierarchy
- Subtle micro-details (hover lifts, focus rings)

OUTPUT: Pure HTML with Tailwind classes (NOT JSX, use class= not className=).
Just the <section> markup, no <html>, no <body>, no markdown wrappers, no explanations.`;

const BRIEF = `Hero section for an analytics SaaS called "Pulse",
in the style of Linear meets Plausible.io.

- Asymmetric: text 60% left, abstract data viz 40% right
- Display headline serif feel, clamp 48-96px
- ONE primary CTA + ONE quiet text link
- 5 customer logo placeholders below at 40% opacity
- Background: subtle data grid pattern at 2% opacity
- Use neutral colors + emerald accent`;

console.log('🚀 Calling Gemini 2.5 Flash...\n');
const startTime = Date.now();

try {
  const result = await model.generateContent([SYSTEM, BRIEF]);
  const response = result.response;
  let html = response.text();

  // Clean up: remove markdown code fences if present
  html = html.replace(/^```html\s*/i, '').replace(/^```\s*/i, '').replace(/```\s*$/i, '').trim();

  const duration = ((Date.now() - startTime) / 1000).toFixed(2);
  const usage = response.usageMetadata;

  console.log('✅ Success!');
  console.log('⏱️  Duration:', duration + 's');
  console.log('📊 Tokens:', usage?.totalTokenCount || 'N/A');
  console.log('💰 Cost: $0.00 (free tier)\n');

  // 🎨 Wrap in a full HTML file with Tailwind CDN for preview
  const fullHTML = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Gemini Test - Pulse Hero</title>
  <script src="https://cdn.tailwindcss.com"></script>
  <link href="https://fonts.googleapis.com/css2?family=Fraunces:wght@300;400;700;900&family=Inter:wght@300;400;500;600;700&display=swap" rel="stylesheet">
  <style>
    body { font-family: 'Inter', system-ui, sans-serif; }
    .font-serif { font-family: 'Fraunces', Georgia, serif; }
  </style>
</head>
<body>
  <!-- Generated by Gemini 2.5 Flash -->
  ${html}

  <!-- Meta info bar -->
  <div class="fixed bottom-4 right-4 bg-black text-white text-xs px-3 py-2 rounded-lg font-mono opacity-80">
    Generated by Gemini 2.5 Flash · ${duration}s · ${usage?.totalTokenCount || 0} tokens · $0.00
  </div>
</body>
</html>`;

  const outputPath = join(__dirname, 'preview.html');
  writeFileSync(outputPath, fullHTML);

  console.log('━'.repeat(60));
  console.log('🎨 PREVIEW READY!');
  console.log('━'.repeat(60));
  console.log('📂 File:', outputPath);
  console.log('');
  console.log('👉 Pour voir le résultat:');
  console.log('   open ' + outputPath);
  console.log('');
  console.log('━'.repeat(60));
} catch (error) {
  console.error('❌ Error:', error.message);
  process.exit(1);
}
